# Generated by Django 2.2.6 on 2019-10-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=150, verbose_name='Lastname')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('photo', models.ImageField(max_length=200, upload_to='photo/', verbose_name='Image')),
                ('credit_card_number', models.CharField(max_length=200, verbose_name='Credit card number')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('abbreviation', models.CharField(max_length=100, verbose_name='Abbrevation')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(max_length=200, upload_to='photo/', verbose_name='Image')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.categories')),
                ('id_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country')),
            ],
        ),
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shopping_date', models.DateField(auto_now=True, verbose_name='Date shopping')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.clients')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.products')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='id_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.country'),
        ),
        migrations.AddField(
            model_name='clients',
            name='id_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.gender'),
        ),
    ]
